name: "GetUsingSystemModules"
description: "Get Using-System Terraform Modules"
inputs:
  working-directory:
    description: "Path of the terraform project"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Checkout devops tf modules
      uses: actions/checkout@v3
      with:
        repository: using-system/devops
        ref: main
        path: devopsrepo

    - name: Copy devops tf modules
      run: cp -R $GITHUB_WORKSPACE/devopsrepo/terraform/modules/* modules/
      working-directory: ${{ inputs.working-dir }}
      shell: :bash
