name: "GitHub comment"
description: "Add or update GitHub comment"
author: "Using-System"
inputs:
  title:
    description: "Comment title"
    required: true
  body:
    description: "Comment body"
    required: true
  github-token:
    description: "GitHub token"
    required: true
runs:
  using: composite
  steps:
    - name: Comment
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const issue_number = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          if (!issue_number) {
            console.log('No issue or pull request number available. Skipping comment creation.');
            return;
          }

          // get all comments
          const comments = await github.rest.issues.listComments({
            issue_number: issue_number,
            owner: owner,
            repo: repo
          });

          // find the comment that contains the identifier
          const title = "${{ inputs.title }}";
          const comment = comments.data.find(comment => comment.body.includes(title));

          const output = `
          <details><summary> ${{ inputs.title }}</summary>
          \n
          ${{ inputs.body }}
          `;

          if (comment) {
            // update the comment
            await github.rest.issues.updateComment({
              comment_id: comment.id,
              owner: owner,
              repo: repo,
              body: output
            });
          } else {
            // create a new comment if no matching comment was found
            await github.rest.issues.createComment({
              issue_number: issue_number,
              owner: owner,
              repo: repo,
              body: output
            });
          }
