name: Validate terraform modules

on:
  push:
    branches:
      - main
    paths:
      - "terraform/modules/**"
      - ".github/workflows/action-validate-tf-module.yml"
  pull_request:
    paths:
      - "terraform/modules/**"
      - ".github/workflows/action-validate-tf-module.yml"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        modules:
          [
            "az-analytics",
            "az-kv",
            "az-nsg",
            "az-rg",
            "az-routetable",
            "az-vnet",
            "core-convention",
            "az-ad-security-group",
            "az-ad-security-group-members",
            "az-iam",
          ]
    defaults:
      run:
        working-directory: "terraform/modules/block-${{ matrix.modules }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terrascan
        uses: ./github/actions/terrascan
        with:
          working-directory: "terraform/modules/block-${{ matrix.modules }}"
          scan-type: "terraform"
          severity: "HIGH"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
