name: Terraform modules documentation

on:
  pull_request:
    paths:
      - "terraform/modules/**"
      - ".github/workflows/tf-modules-doc.yml"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
permissions:
  id-token: write
  contents: write

jobs:
  get-tf-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: get-tf-modules
        name: "Build TF modules matrix"
        run: |
          modules=$(ls -d */ | sed 's#/##' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "modules=$modules" >> $GITHUB_OUTPUT
        working-directory: "terraform/modules/"
    outputs:
      modules: ${{ steps.get-tf-modules.outputs.modules }}

  tf-modules-validation:
    name: Terraform
    needs: get-tf-modules
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        modules: ${{ fromJson(needs.get-tf-modules.outputs.modules) }}
    defaults:
      run:
        working-directory: "terraform/modules/${{ matrix.modules }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: latest

      - name: Terraform Version
        run: terraform version

      - name: Terraform Init
        run: terraform init        

      - name: Terraform Validate
        run: terraform validate

      - name: Render terraform docs and push changes back to PR
        if: github.event_name == 'pull_request'
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: "terraform/modules/${{ matrix.modules }}"
          output-file: README.md
          output-method: inject
          git-push: "true"